name: Space Detection

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd space-detection-frontend 
        npm install 

    - name: Build the Angular project
      run: |
        cd space-detection-frontend  # Yine doğru dizine geçiyoruz
        npm run build --if-present

    - name: Run tests
      run: |
        cd space-detection-frontend  # Testlerin doğru dizinde çalışması için
        npm test -- --watch=false --browsers=ChromeHeadlessCI
