name: Space Detection

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './space-detection-frontend/package-lock.json'  # Cache için doğru path

    - name: Install dependencies
      run: |
        cd space-detection-frontend  # Doğru dizine git
        npm install  # Bağımlılıkları yükle

    - name: Build the Angular project
      run: |
        cd space-detection-frontend  # Doğru dizine git
        npm run build --if-present

    - name: Run tests
      run: |
        cd space-detection-frontend  # Doğru dizine git
        npm test -- --watch=false --browsers=ChromeHeadlessCI
